// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public lifecycle state for a structured view worker, surfaced via
 * `SessionResponse.acp_worker_state` so the sidebar + structured view
 * can show a "Resuming…" affordance while the reconciler is mid-spawn
 * or mid-attach. Deliberately not persisted to the structured view event log:
 * daemon lifecycle is ephemeral, transcript replay should not carry
 * it. See #1088.
 */
export type AcpWorkerState = "absent" | "resuming" | "running" | "stopping";

export type AgentInfo = { kind: AgentKind, name: string, binary: string, host_only: boolean, installed: boolean, install_hint: string, 
/**
 * True when this agent has a one-shot mode (a `oneshot_flag`), so it can
 * be used for the smart-rename title call. The settings smart-rename agent
 * picker filters on this together with `installed`. Always false for
 * custom agents (no built-in one-shot contract).
 */
oneshot_capable: boolean, 
/**
 * True when this agent can run in the structured acp UI: a
 * built-in with an ACP adapter, or a custom agent that declares a
 * valid `agent_acp_cmd`. The web wizard reads this to decide
 * whether a session created for the agent runs in acp or tmux.
 */
acp_capable: boolean, 
/**
 * True when the agent's ACP adapter binary (`acp_command`) is actually
 * resolvable on this host, not just registered. Distinct from
 * `installed` (the agent's own CLI binary) and `acp_capable` (registry
 * knows an adapter exists). The wizard's "Import from Claude" tab gates
 * on this so it never shows when claude-agent-acp is missing. See #2276.
 */
acp_installed: boolean, 
/**
 * True when `[acp] allowed_agents` permits this agent in the structured
 * view. Deliberately separate from `acp_capable`, which states an intrinsic
 * fact (an ACP adapter exists for this agent) that an operator policy does
 * not change. Folding policy into `acp_capable` would hide a disallowed
 * agent from the settings surfaces that enumerate this endpoint to edit
 * per-agent structured-view defaults, which is a legitimate thing to do for
 * an agent that is currently off the allowlist. The wizard gates its
 * structured-view option on this in addition to `acp_capable`. See #3241.
 */
acp_allowed: boolean, 
/**
 * The ACP command a built-in agent launches in acp, e.g.
 * `claude-agent-acp` for claude or `opencode` for opencode. This is
 * the registry command (post `${aoe_data_dir}` substitution), which
 * can differ from `binary`; the wizard previews it so the user sees
 * the real launch command before starting. Omitted for custom
 * agents, whose command values are never serialized here (see the
 * custom-agent serialization tests below).
 */
acp_command?: string, 
/**
 * The registry args appended to `acp_command` (e.g. `["acp"]`
 * for opencode, `["--acp"]` for gemini). Empty when there are none
 * or for custom agents.
 */
acp_args?: Array<string>, 
/**
 * Registry lifecycle state. Omitted while Active so the common wire
 * shape is unchanged; the dashboard renders a deprecated badge in the
 * wizard picker and switch-agent modal.
 */
lifecycle?: AgentLifecycle, };

export type AgentKind = "builtin" | "custom";

/**
 * Data-only lifecycle state. A new variant needs an arm in `AgentDef::lifecycle_label`;
 * the dashboard's copy is generated.
 */
export type AgentLifecycle = { "state": "active" } | { "state": "deprecated", since: string, note: string, replacement: string | null, };

export type AuxiliaryObservation = { target: AuxiliaryTarget, state: PanePresence, tmux_session: string | null, };

export type AuxiliaryTarget = { "kind": "host", index: number, } | { "kind": "container", index: number, } | { "kind": "tool", tool_name: string, };

export type BrowseResponse = { entries: Array<DirEntry>, has_more: boolean, };

/**
 * A discovered Claude Code session, summarized for the import picker.
 */
export type ClaudeSessionSummary = { 
/**
 * The on-disk session id (filename stem). Fed to `session/load`.
 */
session_id: string, 
/**
 * The working directory recorded in the transcript. The structured
 * session must run here for `claude --resume` to resolve the file.
 */
cwd: string, 
/**
 * First human-authored prompt, truncated, for display. `None` when the
 * transcript has no readable user message yet.
 */
title: string | null, 
/**
 * File modification time as a unix epoch millisecond stamp, for
 * recent-first sorting and "last used" display.
 */
last_modified_ms: number, 
/**
 * Whether `cwd` still exists. A resumed session needs its original cwd;
 * the picker flags missing ones.
 */
cwd_exists: boolean, };

export type CleanupDefaults = { delete_worktree: boolean, delete_branch: boolean, delete_sandbox: boolean, 
/**
 * Resolved `session.delete_to_trash`: when true, the web delete dialog
 * defaults to "Move to Trash" with a permanent-delete disclosure;
 * when false it goes straight to permanent delete. See #2489.
 */
delete_to_trash: boolean, };

/**
 * Whether the daemon can preserve agent context during a future authorized
 * lifecycle transition. This is not current start eligibility.
 */
export type ContextResumeAvailability = { "state": "available" } | { "state": "indeterminate", reason: ContextResumeIndeterminateReason, } | { "state": "unavailable", reason: ContextResumeUnavailableReason, };

export type ContextResumeIndeterminateReason = "runtime_check_required" | "agent_handshake_required";

export type ContextResumeUnavailableReason = "agent_unsupported" | "sandbox_unsupported" | "command_unsupported" | "forced_fresh" | "invalid_target" | "fork_pending" | "previous_failure" | "no_target";

export type CreateSessionBody = { title?: string | null, size?: TerminalSize | null, path: string, tool: string, group?: string, yolo_mode?: boolean, 
/**
 * An explicit branch also opts into worktree creation.
 */
worktree_enabled?: boolean, worktree_branch?: string | null, create_new_branch?: boolean, 
/**
 * Used only for new branches; empty selects the repository default.
 */
base_branch?: string | null, sandbox?: boolean, extra_args?: string, sandbox_image?: string | null, extra_env?: Array<string>, extra_repo_paths?: Array<string>, 
/**
 * Repository names or paths override the shared base_branch.
 */
repo_bases?: Array<RepoBaseInput>, command_override?: string, custom_instruction?: string | null, profile?: string | null, 
/**
 * Structured view requires an ACP-capable agent.
 */
view?: View, agent_name?: string | null, agent_model?: string | null, agent_effort?: string | null, 
/**
 * Provision a scratch directory instead of path; excludes worktrees and extra repos.
 */
scratch?: boolean, 
/**
 * Omit to refuse unapproved hooks, false to skip untrusted hooks/MCP, true to approve.
 * Skipping preserves already-trusted repository hooks and MCP.
 */
trust_hooks?: boolean | null, 
/**
 * Require the reviewed configuration to remain unchanged before provisioning.
 */
trust_review?: CreationTrustFingerprint | null, 
/**
 * Resume a Claude conversation through ACP; path must be its original cwd.
 */
import_acp_session_id?: string | null, 
/**
 * Provider conversation ID to fork, mutually exclusive with other sources.
 */
fork_from?: string | null, 
/**
 * Canonical AoE row to fork without supplying its provider conversation ID.
 */
fork_session_id?: string | null, 
/**
 * Completion callback; private and loopback destinations are refused.
 */
callback_url?: string | null, 
/**
 * Persisted replay key, retained until the created row is hard-deleted.
 */
idempotency_key?: string | null, };

/**
 * Captured configuration, rechecked before approval or provisioning.
 */
export type CreationTrustFingerprint = { project_path: string, base_hooks_hash: string, hooks_hash: string | null, mcp_hash: string | null, };

export type DirEntry = { name: string, path: string, is_dir: boolean, is_git_repo: boolean, };

export type DockerStatus = { available: boolean, runtime: string | null, };

/**
 * One configurable field, emitted by the `SettingsSection` derive.
 */
export type FieldDescriptor = { 
/**
 * The `[section]` table in `config.toml` and the profile override key.
 */
section: string, field: string, 
/**
 * TUI tab.
 */
category: string, label: string, description: string, widget: WidgetKind, web_write: WebWritePolicy, 
/**
 * `false` for global-only fields.
 */
profile_overridable: boolean, validation: ValidationKind, 
/**
 * Shown under an "Advanced" fold on both surfaces.
 */
advanced: boolean, 
/**
 * Manifest default for plugin fields; core fields always have a value in `Config`.
 */
default?: unknown, };

export type GroupInfo = { path: string, session_count: number, };

/**
 * One durable ownership protocol for every session lifecycle transition.
 *
 * A transition acquires the per-instance lifecycle flock, then records a
 * fresh generation under `Storage::update`. Terminal launch is the ordered
 * exception: it first takes the app-global per-session title flock so title
 * writers and launch cannot derive different tmux names. The durable
 * reservation stays held through hooks, external side effects, and the
 * exact-generation commit; callers may release outer flocks for reentrant hooks.
 * `status` is presentation state and never proves ownership.
 *
 * A crashed owner loses both the flock and, after the TTL, its reservation.
 * Recovery may then acquire a newer generation; exact-generation commits
 * ensure a late result can never mutate or clear that replacement.
 */
export type LifecycleOperation = "launch" | "capture" | "stop" | "purge" | "restore" | "trash";

export type LifecycleReservation = { op: LifecycleOperation, generation: number, at: string, };

/**
 * A field of a [`WidgetKind::ObjectList`] item.
 */
export type ObjectFieldDescriptor = { field: string, label: string, description?: string, required: boolean, widget: ObjectFieldWidget, validation: ValidationKind, default?: unknown, };

/**
 * A subset of [`WidgetKind`] without object lists, keeping the schema non-recursive.
 */
export type ObjectFieldWidget = { "kind": "toggle" } | { "kind": "text", multiline: boolean, mono: boolean, } | { "kind": "number", min?: number, max?: number, } | { "kind": "select", options: Array<SelectOption>, } | { "kind": "dynamic_select", source: OptionSource, depends_on?: Array<string>, } | { "kind": "dynamic_multi_select", source: OptionSource, depends_on?: Array<string>, } | { "kind": "cron" };

/**
 * Mirrors `aoe_plugin_api::OptionSource`.
 */
export type OptionSource = "acp_agents" | "acp_models" | "acp_modes" | "projects" | "groups";

/**
 * Native handoff requires Alive and the same name as the preparation receipt.
 */
export type PaneObservation = { state: PanePresence, tmux_session: string | null, };

export type PanePresence = "absent" | "alive" | "dead" | "unknown";

/**
 * One unresolved structured (ACP) approval, projected for the home TUI's
 * permission-response dialog. The TUI resolves the `nonce` through the ACP
 * resolver and shows `tool_name` / `target` / `destructive` so the user
 * sees what they are answering without entering the structured view. No
 * dashboard surface renders this; the web client ignores the field.
 */
export type PendingApproval = { nonce: string, tool_name: string, target: string, destructive: boolean, 
/**
 * True when the options are a list of answers (`is_choice_list`), not
 * an allow/deny vocabulary. The home dialog must not answer these by
 * kind; the user picks from the labeled options in the structured
 * view. Defaults false for daemons that predate the field, matching
 * the pre-#3741 projection.
 */
choice: boolean, };

export type PlanSummary = { 
/**
 * First non-completed step's title, truncated to ~80 chars so the
 * sidebar row doesn't overflow.
 */
current_step_title: string | null, 
/**
 * Count of `PlanEntryStatus::Done` steps.
 */
completed: number, 
/**
 * Total step count.
 */
total: number, };

export type ProfileInfo = { name: string, is_default: boolean, description?: string, };

/**
 * Per-project overrides for otherwise-global settings. Every field is
 * `None` when the project doesn't override that setting, so resolution
 * falls through to the global/profile default. Add a field here to make
 * a new global toggle project-overridable; existing call sites that
 * resolve overrides (`find_by_canonical_path`, `resolve_smart_rename_config`)
 * don't need to change shape, only the new call site that consults the
 * new field.
 */
export type ProjectOverrides = { 
/**
 * Overrides `worktree.enabled` (create-worktree-by-default) for new
 * sessions launched against this project.
 */
worktree_enabled?: boolean, 
/**
 * Overrides `session.smart_rename` (agent-driven auto-naming) for
 * sessions launched against this project.
 */
smart_rename?: boolean, };

export type ProjectResponse = { name: string, path: string, scope: ProjectScope, default_base_branch?: string, pinned: boolean, overrides?: ProjectOverrides, };

export type ProjectScope = "global" | "profile";

/**
 * Which ACP `ContentBlock` an attachment maps to. The string form
 * (`"image"` / `"audio"` / `"resource"`) is the wire contract shared
 * with the web composer and the prompt-request DTO in `protocol.rs`,
 * so renaming a variant breaks the build on both sides rather than
 * silently dropping attachments.
 */
export type PromptAttachmentKind = "image" | "audio" | "resource";

/**
 * Replay-side view of one prompt attachment. Carries metadata only,
 * never the bytes: the decoded blob lives in the `acp_attachments`
 * table keyed by `(session_id, id)` and is fetched lazily over
 * `GET /acp/attachments/{id}`. Keeping bytes out of the event log
 * is what stops `event_json` (and every WS replay frame) from bloating
 * to megabytes per screenshot. See #1000 / #965.
 */
export type PromptAttachmentRef = { id: string, kind: PromptAttachmentKind, mime_type: string, name?: string | null, 
/**
 * Decoded byte length, for the UI to show a size hint without
 * fetching the blob.
 */
size: number, };

/**
 * One entry in a session's server-owned prompt queue: a follow-up the
 * user lined up while a turn was busy. The daemon is the source of truth
 * (persisted on the `Instance`), so the queue survives a client reload or
 * a closed PWA and drains on turn-end with no tab open.
 *
 * Attachments carry metadata only, exactly like [`PromptAttachmentRef`]
 * on a live prompt: the bytes live in the event store's pending-attachment
 * table keyed by `(session_id, prompt_id, attachment_id)` (outside the
 * seq-keyed retention prune, since a queued prompt has no event seq yet) and
 * are reloaded at drain time, so a queued screenshot does not bloat the
 * session file.
 */
export type QueuedPromptEntry = { 
/**
 * Client-minted stable id, unchanged across edits. Doubles as the
 * optimistic-echo reconcile key on the client.
 */
id: string, 
/**
 * Server-assigned monotonic order; the queue drains by ascending `seq`.
 */
seq: number, text: string, attachments?: Array<PromptAttachmentRef>, 
/**
 * RFC3339 enqueue time, for retention and provenance.
 */
created_at: string, 
/**
 * Which device enqueued it, for multi-device provenance. `None` for
 * rows migrated from a pre-server-queue client localStorage.
 */
origin_device?: string | null, };

export type RateLimitInfo = { status: string, 
/**
 * When the quota window clears, if the agent reported it.
 */
resets_at: string | null, kind: string, };

export type RepoBase = { 
/**
 * None for single-repo sessions; Some for each workspace member.
 */
repo_name?: string, base_branch: string, 
/**
 * Worktree path this entry's diff was computed in. The web base picker
 * queries it so a workspace member's typeahead lists its own branches
 * rather than the launch repo's (#3329).
 */
repo_path: string, 
/**
 * This entry's explicit override, when set. Absent means `base_branch`
 * came from the creation base, the profile default, or auto-detection, so
 * the client hides its reset affordance (#3329).
 */
base_override?: string, };

/**
 * One repository's branch base in a creation request.
 */
export type RepoBaseInput = { repo: string, base_branch: string, };

export type RichDiffFileInfo = { path: string, old_path?: string, status: RichDiffStatus, additions: number, deletions: number, 
/**
 * Workspace repo this file belongs to, `None` for single-repo sessions.
 * The frontend groups the sidebar list by it and uses it to disambiguate
 * path collisions across repos (#1047).
 */
repo_name?: string, };

export type RichDiffFilesResponse = { files: Array<RichDiffFileInfo>, 
/**
 * One entry per repo whose diff was computed: one element with
 * `repo_name: None` for single-repo sessions, one per member for workspace
 * sessions, since each member can have a different default (#1047).
 */
per_repo_bases: Array<RepoBase>, warning?: string, };

/**
 * [`crate::git::diff::FileStatus`] plus `unchanged`, which the full-file fallback
 * reports for an in-repo path with no diff against the base.
 */
export type RichDiffStatus = "added" | "modified" | "deleted" | "renamed" | "copied" | "untracked" | "conflicted" | "unchanged";

/**
 * Contents-based diff response: raw old/new text that the web client parses
 * and renders itself via `@pierre/diffs`. See [`MAX_CONTENTS_BYTES`].
 */
export type RichFileContentsResponse = { file: RichDiffFileInfo, old_content: string, new_content: string, 
/**
 * Server-computed unified diff of old to new. The client parses it as
 * text rather than re-diffing, which would block the main thread on large
 * files. Empty for binary files.
 */
patch: string, is_binary: boolean, 
/**
 * True if the file was too large to send inline; contents are omitted.
 */
truncated: boolean, };

export type SelectOption = { value: string, label: string, };

/**
 * One session from the daemon. Only `id` is required when decoding.
 */
export type SessionResponse = { id: string, title: string, project_path: string, 
/**
 * Absolute host path of the session's managed artifact directory. The
 * web transcript maps agent-emitted artifact paths under this root (or
 * the fixed sandbox mount) to the authenticated artifact route. See #2587.
 */
artifact_dir: string, group_path: string, tool: string, command: string, extra_args: string, status: string, lifecycle_reservation?: LifecycleReservation | null, lifecycle_generation: number, 
/**
 * True when the session's structured-view worker was auto-stopped for
 * inactivity (resumable/dormant), as opposed to a deliberate Stop. Lets
 * the dashboard render a distinct dormant dot instead of a live-idle one.
 * A deliberate Stop keeps `status: "Stopped"` and reports `false` here.
 * See #2250.
 */
dormant: boolean, idle_dormant_since?: string | null, pane_dead_observed: boolean, agent_pane: PaneObservation, auxiliary: Array<AuxiliaryObservation>, yolo_mode: boolean, created_at: string, last_accessed_at: string | null, 
/**
 * Wall-clock time of the most recent transition into Idle. Used by the
 * web dashboard to fade a freshly-stopped session's color toward neutral.
 * Distinct from `last_accessed_at`: viewing or messaging a session bumps
 * `last_accessed_at` but leaves `idle_entered_at` alone.
 */
idle_entered_at: string | null, last_error: string | null, branch: string | null, main_repo_path: string | null, 
/**
 * Base branch the worktree was created from when AoE managed the
 * creation. None for sessions attached to a pre-existing branch,
 * or those that took the repo's default branch. See #948.
 */
base_branch: string | null, worktree_created_at?: string | null, 
/**
 * Per-session override for the diff base, set via the web "vs &lt;ref&gt;"
 * picker, the TUI diff view's `b` keybind, or
 * `aoe session set-base`. Wins over `base_branch`, the profile
 * default, and auto-detection. See #970.
 */
base_branch_override: string | null, is_sandboxed: boolean, sandbox_container_name?: string | null, 
/**
 * True when the session was created with `--scratch`; the
 * `project_path` points at an auto-provisioned directory under
 * `<app_dir>/scratch/<id>/` that the deletion path removes. The web
 * wizard filters these out of the Recent-projects list.
 */
scratch: boolean, 
/**
 * True when the session is marked as a user favorite. Mirrors
 * `Instance::is_favorited()`; surfaced so the web sidebar can pin
 * favorited rows and render the `*` marker without re-implementing
 * the predicate. Cross-feature parity with the TUI's `f`/`F` keybind.
 */
favorited: boolean, favorited_at?: string | null, 
/**
 * Per-session color label (`red` / `amber` / `green`), or omitted when
 * unset. Rendered as a colored status dot in the web sidebar; set via the
 * sidebar context menu or `aoe session color`. See #2383.
 */
color: string | null, 
/**
 * True when the agent has flagged this session as urgent via the
 * `attention-urgent` hook (read from `/tmp/aoe-hooks-<euid>/{id}/attention.json`
 * by `Instance::is_urgent()`). The web sidebar's Attention sort floats
 * urgent rows above all non-urgent ones within their triage tier,
 * matching the TUI's `attention_session_key` urgent-bias. `is_urgent()`
 * returns false for archived/snoozed sessions, so a sunk row never
 * claws back to the top. See #1640.
 */
urgent: boolean, 
/**
 * RFC3339 timestamp at which the session was web-pinned, or omitted
 * when not pinned. Distinct from `favorited`: favorite is the TUI
 * within-tier attention-sort signal, while pin is the hard
 * top-of-sort surfacing primitive used by the web sidebar. The
 * client derives a "pinned" boolean as `pinned_at != null`; no
 * separate boolean field is exposed (the timestamp itself is the
 * source of truth, matching `archived_at` and `snoozed_until`). See
 * #1581.
 */
pinned_at: string | null, 
/**
 * RFC3339 timestamp at which the session was archived, or omitted
 * when not archived. The web sidebar sinks archived workspaces into
 * the "Snoozed & archived" collapsible section. See #1581.
 */
archived_at: string | null, 
/**
 * RFC3339 timestamp at which a snooze expires, or omitted when not
 * snoozed. The web sidebar treats a non-null future timestamp the
 * same as archived (sinks the workspace) and renders the remaining
 * duration. Expired timestamps are stale-but-harmless: the
 * `Instance::is_snoozed()` predicate returns false past the deadline,
 * and the response simply omits the field. See #1581.
 */
snoozed_until: string | null, 
/**
 * RFC3339 timestamp at which the session was moved to trash, or
 * omitted when not trashed. Trashed rows are excluded from the
 * default session list; the web client requests them with
 * `?state=trashed` and renders a dedicated Trash section with restore
 * and permanent-delete actions. See #2489.
 */
trashed_at: string | null, 
/**
 * Unread marker, mirroring `Instance::unread`: `true` when the session
 * needs attention (a finished turn the user hasn't engaged with, or a
 * manual flag), omitted when read. The web sidebar paints an unread
 * accent and offers a right-click "Mark as read/unread" toggle; gated
 * client-side on the `session.unread_indicator` setting. See the TUI's
 * `theme.unread`.
 */
unread?: boolean, 
/**
 * Strictly a single-repo aoe-managed worktree (`worktree_info`). Drives
 * the sidebar "Edit workdir name" action and the tie-workdir overlay,
 * neither of which applies to multi-repo workspace sessions. For
 * "is there worktree state to clean up on delete", use
 * `has_cleanable_worktree` instead.
 */
has_managed_worktree: boolean, 
/**
 * Whether deleting this session has aoe-managed worktree state to remove,
 * covering single-repo worktrees AND multi-repo workspaces. Only the
 * delete dialog's worktree/branch checkboxes consume this; keeping it
 * separate from `has_managed_worktree` avoids lighting up worktree-only
 * actions (Edit workdir) for workspace sessions (#2363).
 */
has_cleanable_worktree: boolean, 
/**
 * Whether renaming this session also moves its worktree directory (the
 * resolved `session.tie_workdir_to_name` for an aoe-managed worktree).
 * Populated by `list_sessions` from the per-profile config; single-session
 * responses leave it `false` and the sidebar reads the list value. #1927.
 */
tie_workdir_to_name: boolean, 
/**
 * Smart-rename indicator state for structured view sessions: `pending`
 * (still default-named and eligible, will auto-name on the next prompt),
 * `running` (a one-shot title call is in flight), or `inactive`. Populated
 * by `list_sessions`; single-session responses leave it `inactive`. See
 * `session::smart_rename`.
 */
smart_rename: SmartRenameState, 
/**
 * Whether the session still carries its auto-generated civilization name.
 * The sidebar gates the manual "Auto-name now" action on this (it only
 * targets a still-default session, never overwriting a chosen title), and
 * it is a more reliable signal than `smart_rename`: a timed-out one-shot
 * stays `pending` while an unusable-output one goes `inactive`, but both
 * leave the name default and recoverable. Populated by `list_sessions`;
 * single-session responses leave it `false`.
 */
default_name: boolean, has_terminal: boolean, profile: string, cleanup_defaults: CleanupDefaults, remote_owner: string | null, 
/**
 * Host-scoped identity for `remote_owner` ("owner@host"), so the web
 * sidebar's org axis can bucket by this instead of the bare owner: two
 * owners of the same name on different hosts (GitHub "acme" vs GitLab
 * "acme") must never merge into one group or one bulk-archive scope.
 * `remote_owner` stays the display label. Populated the same way and on
 * the same cadence as `remote_owner` (see the cache fill in
 * `list_sessions`); `None` whenever `remote_owner` is `None`.
 */
remote_owner_key: string | null, 
/**
 * Per-session push-notification overrides. None means the session
 * inherits the server-wide default (`web.notify_on_*`) for that
 * event type; Some(true)/Some(false) is an explicit toggle.
 */
notify_on_waiting: boolean | null, notify_on_idle: boolean | null, notify_on_error: boolean | null, 
/**
 * How this session is rendered: `structured` (ACP native rendering) or
 * `terminal` (tmux-backed PTY). The web dashboard branches on this to
 * pick the structured panels vs the terminal view.
 */
view?: View, 
/**
 * Whether the daemon can preserve this agent's context across a future
 * lifecycle transition. This does not report current start eligibility.
 */
context_resume?: ContextResumeAvailability | null, 
/**
 * Live structured view worker lifecycle. `absent` for tmux sessions or
 * structured view sessions whose worker has not been spawned/attached
 * yet; `resuming` while the reconciler is mid-spawn or mid-attach;
 * `running` once the supervisor holds a live worker. Drives the
 * sidebar `Resuming…` chip and the per-session banner in the
 * structured view. See #1088.
 */
acp_worker_state: AcpWorkerState, 
/**
 * Unresolved structured approvals in request order, projected only for
 * live (`running` worker) structured sessions. The TUI uses these to
 * route the existing permission-response dialog through the ACP
 * resolver and to show what is being approved; no dashboard surface
 * renders them.
 */
pending_approvals?: Array<PendingApproval>, 
/**
 * The provider rate limit this session is parked on, read from the
 * daemon's durable park rather than a browser-side mirror, so the
 * sidebar badge clears when a resume lands with no tab open (#3514).
 */
rate_limit?: RateLimitInfo | null, 
/**
 * Whether `[acp] rate_limit_auto_resume` is on for this session's
 * profile, so the rate-limit banner can say whether the park ends by
 * itself. Set by the list handler; omitted by single-session responses,
 * whose readers keep the value they last saw.
 */
rate_limit_auto_resume?: boolean | null, 
/**
 * True when this session's agent can run in structured view: a built-in
 * with an ACP adapter, or a custom agent whose profile config
 * declares a valid `agent_acp_cmd`. The web terminal view reads
 * this to decide whether the "switch to structured view" affordance is
 * available, replacing the hardcoded client-side tool list.
 */
acp_capable: boolean, 
/**
 * The session's server-owned prompt queue (follow-ups the user lined up
 * while a turn was busy), ordered by `seq`. The daemon owns it, so it is
 * visible across the user's devices and survives a client reload; the
 * structured view renders it and drains happen server-side.
 */
queued_prompts?: Array<QueuedPromptEntry>, 
/**
 * The session's captured ACP session id, present only once the
 * structured-view worker has minted one. The web dashboard passes this
 * as `fork_from` on a structured fork create and gates the "Fork" action
 * on it together with `acp_can_fork`. Omitted when absent (terminal
 * sessions, or structured ones whose worker has not minted an id yet).
 */
acp_session_id: string | null, 
/**
 * The session's resolved ACP registry key (`agent_name` when set, else
 * `tool`), matching the `name` entries `/api/acp/agents` returns. The
 * structured view's switch-agent modal reads this as the current-agent
 * fallback before the first `AgentSwitched` event lands (which is the
 * only event that populates the reduced `state.agent`), so it can gray
 * out the running backend on a never-switched session. Omitted for
 * sessions with no resolved agent. See #2803.
 */
acp_agent: string | null, 
/**
 * True when this session's agent can run a structured ACP `session/fork`,
 * per `crate::session::fork::structured_fork_capable`. Resume-only ACP
 * agents (e.g. `aoe-agent`) are ACP-capable yet not forkable, so the web
 * gates "Fork" on this AND `acp_session_id` rather than on a captured id
 * alone. Omitted (read as not-forkable) for terminal sessions and
 * non-forkable agents.
 */
acp_can_fork?: boolean, 
/**
 * Whether switching this session between terminal and structured view
 * preserves the conversation (only claude pairings share one
 * CLI-resumable transcript). Server-owned via
 * `agents::acp_transcript_cli_resumable` so the dashboard and TUI stop
 * each recomputing it from `tool` + `acp_agent`. Omitted for
 * non-preserving pairings.
 */
keeps_context?: boolean, 
/**
 * Slash-command aliases that reset the conversation for this session's
 * agent (claude `/clear`, codex/opencode `/new`). Server-owned from
 * `acp::agent_profiles::resolve(...).clear_aliases` so the composer's `/`
 * palette and queued-prompt batching do not mirror the per-agent list.
 * Omitted for agents with no clear alias.
 */
clear_aliases?: Array<string>, 
/**
 * True when the session is a Claude Code session AND the user has
 * enabled Claude's fullscreen renderer (`tui: "fullscreen"` in
 * `~/.claude/settings.json`). The web client uses this to skip
 * scrollback-tracking workarounds that target tmux copy-mode.
 */
claude_fullscreen: boolean, 
/**
 * Repos in the multi-repo workspace (empty for single-repo sessions).
 * Each entry mirrors `WorkspaceRepo` minus paths the dashboard does
 * not need to display.
 */
workspace_repos: Array<WorkspaceRepoSummary>, workspace_dir?: string | null, workspace_branch?: string | null, workspace_created_at?: string | null, workspace_cleanup_on_delete?: boolean | null, 
/**
 * Non-fatal warnings surfaced by a mutation response. On create these are
 * worktree-creation warnings (e.g. post-checkout hook failures where the
 * worktree was still created successfully). On rename these carry the
 * tmux rekey warning emitted when the title was persisted durably but the
 * live tmux session could not be renamed afterwards. Both live on the
 * response only: the field is not persisted to the instance, so it is
 * omitted from list/fetch responses.
 */
warnings?: Array<string>, 
/**
 * Latest plan snapshot summarised for the sidebar. Present only on
 * structured view sessions whose agent has emitted a Plan (directly via
 * ACP `SessionUpdate::Plan` or indirectly via the ExitPlanMode
 * bridge in `acp_client::map_update_to_events`). See #1061.
 */
plan_summary: PlanSummary | null, 
/**
 * Absolute RFC3339 timestamp at which the structured view session's
 * `ScheduleWakeup` tool will fire (i.e. the next turn is expected
 * to start). Cleared once a `UserPromptSent` lands after the
 * scheduling tool call; the /loop skill's self-firing emits that
 * prompt at wake time, so a wakeup whose seq is ≤ the latest
 * prompt has already fired. See #1091.
 */
next_wakeup_at: string | null, 
/**
 * User-facing reason the agent gave when scheduling the wakeup,
 * shown alongside the countdown chip / banner. Only set when
 * `next_wakeup_at` is also set. See #1091.
 */
next_wakeup_reason: string | null, 
/**
 * True when the structured view session has an armed `Monitor` tool
 * (a background watch). Unlike a scheduled wakeup there is no fire
 * time, so the sidebar shows a static "monitoring" badge rather than a
 * countdown. Cleared once a `UserPromptSent` lands after the monitor
 * was armed (the user took over).
 */
monitor_active?: boolean, 
/**
 * The `description` the agent gave the `Monitor` tool, shown as the
 * badge tooltip. Only set when `monitor_active` is true.
 */
monitor_description: string | null, };

/**
 * Per-session smart-rename state surfaced to the dashboard so the sidebar can
 * show that a session will be (or is being) auto-named. `Inactive` for
 * sessions that are not eligible or already renamed.
 */
export type SmartRenameState = "inactive" | "pending" | "running";

export type TerminalSize = { cols: number, rows: number, };

/**
 * Server-authoritative validation applied before a value is merged.
 */
export type ValidationKind = { "rule": "none" } | { "rule": "range_u64", min: number, max: number | null, } | { "rule": "non_empty_string" } | { "rule": "str" } | { "rule": "str_list" } | { "rule": "bool" } | { "rule": "range_i64", min: number | null, max: number | null, } | { "rule": "memory_limit" } | { "rule": "volume_list" } | { "rule": "env_list" } | { "rule": "port_mapping_list" } | { "rule": "capability_list" } | { "rule": "security_opt_list" } | { "rule": "network" } | { "rule": "one_of", options: Array<string>, } | { "rule": "cron" } | { "rule": "object_list", id_field: string, fields: Array<ObjectFieldDescriptor>, min_items: number | null, max_items: number | null, };

/**
 * How a session is rendered. `Structured` uses the ACP-based native
 * rendering (plan panels, tool-call cards, approvals); `Terminal` streams
 * the raw tmux/PTY through xterm.js. `Terminal` is the conservative
 * deserialization default; session creation sets the value explicitly.
 */
export type View = "terminal" | "structured";

export type WebWritePolicy = { "policy": "allow" } | { "policy": "requires_elevation", reason: string, } | { "policy": "local_only", reason: string, };

export type WidgetKind = { "kind": "toggle" } | { "kind": "text", multiline: boolean, mono: boolean, } | { "kind": "optional_text", mono: boolean, } | { "kind": "number", min?: number, max?: number, } | { "kind": "slider", min: number, max: number, step: number, } | { "kind": "select", options: Array<SelectOption>, } | { "kind": "list" } | { "kind": "dynamic_select", source: OptionSource, depends_on?: Array<string>, } | { "kind": "object_list", id_field: string, fields: Array<ObjectFieldDescriptor>, min_items?: number, max_items?: number, } | { "kind": "cron" } | { "kind": "custom", id: string, };

export type WorkspaceRepoSummary = { name: string, source_path: string, branch: string, worktree_path: string, main_repo_path: string, managed_by_aoe: boolean, branch_preexisting: boolean, base_branch?: string | null, base_branch_override?: string | null, };
