// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client to daemon. Binary messages are pane input and carry no envelope.
 */
export type LiveClientMessage = { "type": "resize", cols: number, rows: number, } | { "type": "window", lines: number, } | { "type": "cadence", fast: boolean, } | { "type": "claim_if_vacant" } | { "type": "claim" } | { "type": "caps", deflate: boolean, patch: boolean, 
/**
 * What another client calls this one in its "took over" notice.
 */
label?: string | null, } | { "type": "resync" } | { "type": "wheel", up: boolean, col: number, row: number, 
/**
 * Notches this stands for. Absent means one, which is what a client
 * predating coalescing sends.
 */
count: number, };

/**
 * Cursor position, already translated onto the window grid by the daemon.
 * Clients must not add a composite origin to it a second time.
 */
export type LiveCursor = { x: number, y: number, };

/**
 * Pane 0's rectangle inside a composited window. Input is pinned to pane 0,
 * so a client maps pointer cells against this rather than the whole window.
 */
export type LivePane0 = { cols: number, rows: number, left: number, top: number, };

/**
 * The pane state every content message carries. Each field defaults, so a
 * frame from a daemon that predates one of them still parses.
 */
export type LivePaneMeta = { 
/**
 * Rows of live screen at the end of `content`; the rest is history.
 */
rows: number, 
/**
 * Lines in the pane's scrollback, for a client sizing a scroll spacer.
 */
history: number, cursor: LiveCursor | null, 
/**
 * `#{alternate_on}`: a full-screen app, so there is no scrollback to
 * widen and the wheel belongs to the app.
 */
altScreen: boolean, 
/**
 * `#{mouse_any_flag}`: the app asked for button reports.
 */
mouse: boolean, 
/**
 * `#{mouse_sgr_flag}`: SGR (1006) encoding rather than legacy X10.
 */
mouseSgr: boolean, 
/**
 * `#{mouse_all_flag}`: any-event tracking (1003), so the app wants bare
 * motion and a viewer can forward hover.
 */
mouseAll: boolean, pane0?: LivePane0 | null, };

/**
 * Daemon to client.
 */
export type LiveServerMessage = { "type": "frame", 
/**
 * Absent only from a daemon that predates sequencing, which then
 * cannot send patches either.
 */
seq?: number | null, content: string, 
/**
 * Rows of live screen at the end of `content`; the rest is history.
 */
rows: number, 
/**
 * Lines in the pane's scrollback, for a client sizing a scroll spacer.
 */
history: number, cursor: LiveCursor | null, 
/**
 * `#{alternate_on}`: a full-screen app, so there is no scrollback to
 * widen and the wheel belongs to the app.
 */
altScreen: boolean, 
/**
 * `#{mouse_any_flag}`: the app asked for button reports.
 */
mouse: boolean, 
/**
 * `#{mouse_sgr_flag}`: SGR (1006) encoding rather than legacy X10.
 */
mouseSgr: boolean, 
/**
 * `#{mouse_all_flag}`: any-event tracking (1003), so the app wants bare
 * motion and a viewer can forward hover.
 */
mouseAll: boolean, pane0?: LivePane0 | null, } | { "type": "patch", seq: number, base: number, shift: number, lines: Array<[number, string]>, 
/**
 * Rows of live screen at the end of `content`; the rest is history.
 */
rows: number, 
/**
 * Lines in the pane's scrollback, for a client sizing a scroll spacer.
 */
history: number, cursor: LiveCursor | null, 
/**
 * `#{alternate_on}`: a full-screen app, so there is no scrollback to
 * widen and the wheel belongs to the app.
 */
altScreen: boolean, 
/**
 * `#{mouse_any_flag}`: the app asked for button reports.
 */
mouse: boolean, 
/**
 * `#{mouse_sgr_flag}`: SGR (1006) encoding rather than legacy X10.
 */
mouseSgr: boolean, 
/**
 * `#{mouse_all_flag}`: any-event tracking (1003), so the app wants bare
 * motion and a viewer can forward hover.
 */
mouseAll: boolean, pane0?: LivePane0 | null, } | { "type": "size_owner", is_owner: boolean, holder?: string | null, } | { "type": "clipboard", text: string, } | { "type": "transport", grid: boolean, maxWindow: number, };
