//! Pure fork-eligibility logic and the one-shot fork seed a new session
//! carries. No tmux, no daemon: this is the decision layer the TUI, CLI, and
//! web all consult so "can I fork this?" is answered identically everywhere.

use crate::agents::{get_agent, ForkStrategy};

/// The kind of one-shot fork a freshly-created session should perform on its
/// first launch. Terminal sessions resume the parent agent id with a fork
/// flag and a pre-pinned child id; structured sessions ask the ACP adapter to
/// fork and capture the minted id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ForkSeed {
    /// Terminal fork: resume `parent_agent_session_id` with the agent's fork
    /// flag, writing to the pre-generated `child_session_id`.
    Terminal {
        parent_agent_session_id: String,
        child_session_id: String,
    },
    /// Structured fork: send ACP `session/fork` against
    /// `parent_acp_session_id`; the adapter mints the child id.
    Structured { parent_acp_session_id: String },
}

/// Why a fork was refused, for a user-facing message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ForkDenied {
    /// The agent's CLI has no fork capability (terminal path).
    AgentCannotFork,
    /// No captured session id to fork from yet (the parent never started a
    /// conversation, or its id hasn't been observed).
    NoParentSession,
}

/// Decide whether a TERMINAL session can be forked, and if so produce the
/// seed. `child_session_id` is pre-generated by the caller (a fresh Claude
/// UUID) so the forked id is durable before launch.
pub fn terminal_fork_seed(
    tool: &str,
    parent_agent_session_id: Option<&str>,
    child_session_id: String,
) -> Result<ForkSeed, ForkDenied> {
    let agent = get_agent(tool).ok_or(ForkDenied::AgentCannotFork)?;
    if matches!(agent.fork_strategy, ForkStrategy::Unsupported) {
        return Err(ForkDenied::AgentCannotFork);
    }
    let parent = parent_agent_session_id
        .filter(|s| !s.is_empty())
        .ok_or(ForkDenied::NoParentSession)?;
    Ok(ForkSeed::Terminal {
        parent_agent_session_id: parent.to_string(),
        child_session_id,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_with_parent_id_yields_terminal_seed() {
        let seed = terminal_fork_seed("claude", Some("parent-uuid"), "child-uuid".into());
        assert_eq!(
            seed,
            Ok(ForkSeed::Terminal {
                parent_agent_session_id: "parent-uuid".into(),
                child_session_id: "child-uuid".into(),
            })
        );
    }

    #[test]
    fn resume_only_agent_is_denied() {
        assert_eq!(
            terminal_fork_seed("gemini", Some("parent-uuid"), "child-uuid".into()),
            Err(ForkDenied::AgentCannotFork)
        );
    }

    #[test]
    fn missing_parent_id_is_denied() {
        assert_eq!(
            terminal_fork_seed("claude", None, "child-uuid".into()),
            Err(ForkDenied::NoParentSession)
        );
        assert_eq!(
            terminal_fork_seed("claude", Some(""), "child-uuid".into()),
            Err(ForkDenied::NoParentSession)
        );
    }
}
